Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08c40ec9ead489470  # Amazon Linux 2 (us-east-1)
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !ImportValue DevOpsSubnetId

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      VpcId: !ImportValue DevOpsVPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  EC2PublicIP:
    Description: Public IP da instância
    Value: !GetAtt EC2Instance.PublicIp
