AWSTemplateFormatVersion: "2010-09-09"
Description: "Template para criar uma instância EC2 Free Tier"

Parameters:
  KeyName:
    Description: Nome do par de chaves para acessar a instância
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Description: Tipo da instância EC2
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: deve ser um tipo de instância Free Tier.

  LatestAmiId:
    Description: AMI Amazon Linux 2023 Free Tier para us-east-1
    Type: AWS::EC2::Image::Id
    Default: ami-00ca32bbc84273381

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref LatestAmiId
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !ImportValue DevOps-SubnetPublica
      CreditSpecification:
        CpuCredits: standard  # Garante Free Tier

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Habilitar acesso SSH e HTTP
      VpcId: !ImportValue DevOps-VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: ID da instância EC2
    Value: !Ref EC2Instance

  PublicIP:
    Description: Endereço IP público da instância
    Value: !GetAtt EC2Instance.PublicIp
