AWSTemplateFormatVersion: '2010-09-09'
Description: Template para criar uma VPC simples com subnet pública e Internet Gateway

Resources:
  # Cria a VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: DevOps-VPC

  # Cria a Subnet Pública
  SubnetPublica:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: DevOps-SubnetPublica

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: DevOps-IGW

  # Associação do IGW à VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Route Table Pública
  RouteTablePublica:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: DevOps-RouteTablePublica

  # Rota para Internet
  RotaInternet:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTablePublica
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Associação da Subnet Pública à Route Table
  AssociaSubnetPublica:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPublica
      RouteTableId: !Ref RouteTablePublica

Outputs:
  VPCId:
    Description: ID da VPC criada
    Value: !Ref VPC
    Export:
      Name: DevOps-VPC

  SubnetPublica:
    Description: ID da Subnet Pública criada
    Value: !Ref SubnetPublica
    Export:
      Name: DevOps-SubnetPublica
