name: CI Pipeline - Python + Deploy AWS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build e Testes Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Rodar testes e gerar relatório JUnit
        run: |
          pytest -q --junitxml=reports/junit.xml

      - name: Publicar relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml

  deploy-infra:
    name: Deploy Infraestrutura AWS
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy VPC
        run: |
          aws cloudformation deploy \
            --template-file infra/vpc.yml \
            --stack-name devops-vpc \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy S3
        run: |
          aws cloudformation deploy \
            --template-file infra/s3.yml \
            --stack-name devops-s3 \
            --capabilities CAPABILITY_NAMED_IAM

      # EC2 porque ela já foi criada manualmente
      # - name: Deploy EC2
      #   run: |
      #     aws cloudformation deploy \
      #       --template-file infra/ec2.yml \
      #       --stack-name devops-ec2 \
      #       --capabilities CAPABILITY_NAMED_IAM \
      #       --parameter-overrides KeyName=devops-key
