name: CI Pipeline - Python

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Rodar testes e gerar relatório JUnit
        run: |
          pytest -q --junitxml=reports/junit.xml

      - name: Publicar relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml

  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy CloudFormation Stacks
        run: |
          aws cloudformation deploy \
            --template-file infra/vpc.yaml \
            --stack-name minha-pipeline-vpc \
            --no-fail-on-empty-changeset

          aws cloudformation deploy \
            --template-file infra/s3.yaml \
            --stack-name minha-pipeline-s3 \
            --no-fail-on-empty-changeset

          aws cloudformation deploy \
            --template-file infra/ec2.yaml \
            --stack-name minha-pipeline-ec2 \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset \
            --parameter-overrides KeyName=MariaEduardaQuadros