name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: pytest --junitxml=report.xml

      - name: Publicar relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: report.xml

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Comentando o deploy AWS porque os recursos já existem
      # - name: Deploy da VPC
      #   run: |
      #     aws cloudformation deploy \
      #       --template-file infra/vpc.yml \
      #       --stack-name devops-vpc \
      #       --capabilities CAPABILITY_NAMED_IAM \
      #       --no-fail-on-empty-changeset

      # - name: Deploy do S3
      #   run: |
      #     aws cloudformation deploy \
      #       --template-file infra/s3.yml \
      #       --stack-name devops-s3 \
      #       --capabilities CAPABILITY_NAMED_IAM \
      #       --no-fail-on-empty-changeset

      # - name: Deploy da EC2
      #   run: |
      #     aws cloudformation deploy \
      #       --template-file infra/ec2.yml \
      #       --stack-name devops-ec2 \
      #       --capabilities CAPABILITY_NAMED_IAM \
      #       --no-fail-on-empty-changeset
